name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Install LaTeX
        run: | 
          sudo apt update
          sudo apt install -y make latex-cjk-all texlive-xetex texlive-latex-extra texlive-fonts-extra fonts-noto-cjk fonts-font-awesome poppler-utils
      - name: Build
        run: make all
      - name: Combine en and zh PDF
        run: pdfunite resume.pdf resume-zh.pdf resume_en-and-zh.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.head_commit.message }}
          files: |
            resume-zh.pdf
            resume.pdf
            resume_en-and-zh.pdf