name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Install LaTeX
        run: sudo apt install -y make texlive-xetex texlive-latex-extra texlive-fonts-extra fonts-noto-cjk fonts-font-awesome
      - name: Build
        run: make all
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          files: resume-zh.pdf